# filepath: netlify.toml
[build]
  command   = "npm run build"
  publish   = ".output/public"
  functions = ".output/server"

[build.environment]
  NODE_ENV     = "production"
  NITRO_PRESET = "netlify"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200