services:
  - type: web
    name: mon-app-nuxt
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
